### ISSUE TITLE
An error is thrown if no response after 2 minutes

### ISSUE THREAD

**Issue by hong6234** [ForbesLindesay/sync-rpc#3]
Error: nodeNC failed:\n\nevents.js:167
      throw er; // Unhandled 'error' event
      	Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:    
at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at sendMessage (D:\\root\\node_modules\\sync-rpc\\lib\\index.js:130:13)
    at D:\\root\\node_modules\\sync-rpc\\lib\\index.js:159:25
    at request (D:\\root\\node_modules\\sync-request\\lib\\index.js:28:15)
    at FuncLib.func_server (D:\\root\\funclib.js:529:26)
    at FuncLib.export_wrap (D:\\root\\funclib.js:547:31)
    at FuncLib.GetPowerPlanGuidByName (D:\\root\\funclib.js:484:58)
    at Object.module.exports.template.Case.step [as step_func] (D:\\root\\case_scripts\\test app\\test case 01\\main.js:16:39)
    at Case.run (D:\\root\\template.js:183:35)
    at Object.<anonymous> (d:\\root\\run_script.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:685:14

**Comment by hong6234** [comment]
I fix it myself.
by append `setKeepAlive(true)` to `nodeNetCatSrc` in index.js
`function nodeNetCatSrc(port, input) {
  return (
    "var c=require('net').connect(" +
    port +
    ",'127.0.0.1',()=>{c.pipe(process.stdout);c.end(" +
    JSON.stringify(input)
      .replace(/\u2028/g, '\\u2028')
      .replace(/\u2029/g, '\\u2029') +
    ')}).setKeepAlive(true);'
  );
}`
